#! /bin/sh

set -e

# Stop Subsonic service.
if [ -e /etc/init.d/subsonic ]; then
  invoke-rc.d subsonic stop
fi

# Backup database.
if [ -e /var/booksonic/db ]; then
  rm -rf /var/booksonic/db.backup
  cp -R /var/booksonic/db /var/booksonic/db.backup
fi

